<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="growSimpleEnd.map" md5sum="1a858c71c7df562857ee0ce9f66fa1ba" version="7.5.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		growSimpleEnd.map
*   Map declaration(s):	growSimpleEnd
*   Input file(s):		file:/C:/WID/64-bit/Simple/simpleTestIn.xsd
*   Output file(s):		file:/C:/WID/64-bit/Simple/simpleTestOut.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:io="http://Simple"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:map="http://Simple/growSimpleEnd"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="str set math fn regexp dyn dp exsl date dp str map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io:simpleTestOut_._type'"/>
            </xsl:attribute>
            <xsl:call-template name="map:growSimpleEnd2">
              <xsl:with-param name="simpleTestIn" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io:simpleTestIn" mode="map:growSimpleEnd"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:simpleTestIn" to "io:simpleTestOut".  -->
  <xsl:template match="io:simpleTestIn"  mode="map:growSimpleEnd">
    <io:simpleTestOut>
      <xsl:call-template name="map:growSimpleEnd2">
        <xsl:with-param name="simpleTestIn" select="."/>
      </xsl:call-template>
    </io:simpleTestOut>
  </xsl:template>

  <!-- This rule represents a type mapping: "io:simpleTestIn" to "io:simpleTestOut".  -->
  <xsl:template name="map:growSimpleEnd2">
    <xsl:param name="simpleTestIn"/>
    <!-- a simple data mapping: "$simpleTestIn/stringTwo"(string) to "numberOne"(float) -->
    <xsl:if test="$simpleTestIn/stringTwo">
      <numberOne>
        <!-- variables for custom code -->
        <xsl:variable name="stringTwo2" select="$simpleTestIn/stringTwo"/>
        <xsl:value-of select="string-length($stringTwo2)"/>
      </numberOne>
    </xsl:if>
    <!-- a simple data mapping: "$simpleTestIn/stringThree"(string) to "numberTwo"(float) -->
    <xsl:if test="$simpleTestIn/stringThree">
      <numberTwo>
        <!-- variables for custom code -->
        <xsl:variable name="stringThree2" select="$simpleTestIn/stringThree"/>
        <xsl:value-of select="string-length($stringThree2)"/>
      </numberTwo>
    </xsl:if>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
