<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="growSimpleBegin.map" md5sum="b661829bf83b5ec7a9d4d109c4203dc7" version="7.5.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		growSimpleBegin.map
*   Map declaration(s):	growSimpleBegin
*   Input file(s):		simpleTestBegin.xsd
*   Output file(s):		simpleTestIn.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:io="http://Simple"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:map="http://Simple/growSimpleBegin"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="str set math fn regexp dyn dp exsl date str map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io:simpleTestIn_._type'"/>
            </xsl:attribute>
            <xsl:call-template name="map:growSimpleBegin2">
              <xsl:with-param name="simpleTestBegin" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io:simpleTestBegin" mode="map:growSimpleBegin"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:simpleTestBegin" to "io:simpleTestIn".  -->
  <xsl:template match="io:simpleTestBegin"  mode="map:growSimpleBegin">
    <io:simpleTestIn>
      <xsl:call-template name="map:growSimpleBegin2">
        <xsl:with-param name="simpleTestBegin" select="."/>
      </xsl:call-template>
    </io:simpleTestIn>
  </xsl:template>

  <!-- This rule represents a type mapping: "io:simpleTestBegin" to "io:simpleTestIn".  -->
  <xsl:template name="map:growSimpleBegin2">
    <xsl:param name="simpleTestBegin"/>
    <io:simpleArray>
      <!-- a simple data mapping: "$simpleTestBegin/stringOne"(string) to "arrayOne"(string) -->
      <xsl:element name="arrayOne">
        <xsl:value-of select="$simpleTestBegin/stringOne"/>
      </xsl:element>
    </io:simpleArray>
    <!-- a simple data mapping: "$simpleTestBegin/stringOne"(string) to "algorithm"(string) -->
    <algorithm>
      <xsl:value-of select="$simpleTestBegin/stringOne"/>
    </algorithm>
    <!-- a simple data mapping: "$simpleTestBegin/stringOne"(string) to "stringTwo"(string) -->
    <stringTwo>
      <!-- variables for custom code -->
      <xsl:variable name="stringOne" select="$simpleTestBegin/stringOne"/>
      <xsl:variable name="lengthOne" select="$simpleTestBegin/lengthOne"/>
      <xsl:value-of select="str:padding($lengthOne, $stringOne)"/>
    </stringTwo>
    <!-- a simple data mapping: "$simpleTestBegin/stringTwo"(string) to "stringThree"(string) -->
    <stringThree>
      <!-- variables for custom code -->
      <xsl:variable name="stringTwo" select="$simpleTestBegin/stringTwo"/>
      <xsl:variable name="lengthTwo" select="$simpleTestBegin/lengthTwo"/>
      <xsl:value-of select="str:padding($lengthTwo, $stringTwo)"/>
    </stringThree>
    <!-- a simple data mapping: "$simpleTestBegin/stringTwo"(string) to "stringFour"(string) -->
    <stringFour>
      <xsl:value-of select="$simpleTestBegin/stringTwo"/>
    </stringFour>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
