apiVersion: v1
kind: Pod
metadata:
    name: datapower
    labels:
        app: datapower
spec:
    containers:
      -
        name: "datapower"
        image: ibmcom/datapower:latest
        stdin: true
        tty: true
        env:
        - name: DATAPOWER_ACCEPT_LICENSE
          value: "true"
        - name: DATAPOWER_INTERACTIVE
          value: "true"
